# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'OC_APP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OC_APP

pod 'MBProgressHUD'
pod 'SDWebImage'

pod 'AFNetworking'
pod 'YYCache' #缓存

pod 'MJRefresh'
pod 'MJExtension'

pod 'pop' #做动画效果

pod 'Masonry' #布局

pod 'TZImagePickerController' #图片选择器

pod 'WebViewJavascriptBridge' #web js交互

end
